name: math_derust
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.1
  rive: ^0.13.20
  supabase_flutter: ^2.9.0
  supabase: ^2.7.0
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  image_path: "icons/android.png"                                                                                                   
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/checkmark_icon.riv
    - assets/error_icon.riv
    - assets/google_logo.png
    - .env